Repository owncloud/oauth2, pull requests merged in 2018-12, with the labels that each got.

#183 Prepare for 0.3.0 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review

#185 Release 0.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review

#186 Standardize CI setup
  .drone.yml
  .gitignore
  .phan/config.php
  .php_cs.dist
  Makefile
  composer.json
  composer.lock
  phpstan.neon
  phpunit.xml
  tests/bootstrap.php
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, Drone, QA-team

#187 use bootstrap.php of core acceptance tests
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#188 the currently logged in user is visible and an option to …
  lib/Controller/PageController.php
  templates/authorize.php
  tests/Unit/Controller/PageControllerTest.php
Labels: 3 - To review
