Repository owncloud/oauth2, pull requests merged in 2018-11, with the labels that each got.

#175 Adjust acceptance test steps changed in core
  tests/acceptance/features/webUIOauth2/enforceTokenAuth.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#178 Add occ oauth2:remove-client to remove a client by it\s id
  appinfo/info.xml
  lib/Commands/RemoveClient.php
Labels: 3 - To review

#179 adjust acceptance test time constant names
  tests/acceptance/features/lib/Oauth2AuthRequestPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#180 Set max version to 10 for Semver
  appinfo/info.xml
Labels: 3 - To review

#173 Autofocus added to buttons
  templates/authorize-error.php
  templates/authorize.php
  templates/switch-user.php
Labels: 4 - To release
