Repository owncloud/oauth2, pull requests merged in 2019-02, with the labels that each got.

#192 Do not delete COMPOSER_BIN on clean-composer-deps
  Makefile
Labels: 4 - To release, QA-team

#195 Delete vendor when doing clean-deps
  Makefile
Labels: 4 - To release, QA-team

#197 The redirect_uri needs to be encoded in the logout url
  lib/Controller/PageController.php
Labels: 3 - To review

#198 read the skeleton file through the testing app not directly
  tests/acceptance/features/bootstrap/Oauth2Context.php
Labels: 4 - To release, QA-team, dev:acceptance-tests
