Repository owncloud/oauth2, pull requests merged in 2019-12, with the labels that each got.

#237 Improve adding a new client
  css/main.css
  js/settings-admin.js
  lib/Commands/AddClient.php
  lib/Controller/SettingsController.php
  lib/Db/ClientMapper.php
  lib/Panels/AdminPanel.php
  templates/authorize.php
  templates/client.part.php
  templates/settings-admin.php
  templates/settings-personal.php
  tests/Unit/Controller/SettingsControllerTest.php
  tests/Unit/Panel/AdminPanelTest.php
  tests/acceptance/features/lib/Oauth2AdminSettingsPage.php
Labels: 3 - To review

#240 Adjust tests
  .drone.starlark
  .drone.yml
  tests/Unit/AuthModuleTest.php
  tests/Unit/Controller/OAuthApiControllerTest.php
  tests/Unit/Controller/OpenIdConnectControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Controller/SettingsControllerTest.php
  tests/Unit/Db/AccessTokenMapperTest.php
  tests/Unit/Db/AccessTokenTest.php
  tests/Unit/Db/AuthorizationCodeMapperTest.php
  tests/Unit/Db/AuthorizationCodeTest.php
  tests/Unit/Db/ClientMapperTest.php
  tests/Unit/Db/RefreshTokenMapperTest.php
  tests/Unit/Hooks/UserHooksTest.php
  tests/Unit/Panel/AdminPanelTest.php
  tests/Unit/Sabre/OAuth2Test.php
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#242 Add sabre/xml to behat dependencies
  .drone.starlark
  .drone.yml
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team, dev:acceptance-tests

#243 Coding standard 2.0.0
  .drone.starlark
  tests/Unit/AuthModuleTest.php
  tests/Unit/Db/AccessTokenMapperTest.php
  tests/Unit/Db/AuthorizationCodeMapperTest.php
  tests/Unit/Db/ClientMapperTest.php
  tests/Unit/Db/RefreshTokenMapperTest.php
  vendor-bin/owncloud-codestyle/composer.json
Labels: 4 - To release, QA-team

#247 Fix: fail due to unneeded variable removal in webDavHelper
  tests/acceptance/features/bootstrap/Oauth2Context.php
Labels: 3 - To review, QA-team

#244 Merge Release 0.4.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review
