Repository owncloud/oauth2, pull requests merged in 2020-04, with the labels that each got.

#259 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To review, QA-team

#263 [Tests-Only] Bump phan 2.7 & Run phan in CI
  .drone.star
  .phan/config.php
  lib/AppInfo/Application.php
  lib/AuthModule.php
  lib/Commands/AddClient.php
  lib/Commands/RemoveClient.php
  lib/Controller/OAuthApiController.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Db/AccessTokenMapper.php
  lib/Hooks/UserHooks.php
  lib/Panels/AdminPanel.php
  lib/Panels/PersonalPanel.php
  lib/Sabre/OAuth2.php
  vendor-bin/phan/composer.json
Labels: QA-team

#264 Implement phpunit v8
  .gitignore
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Db/AccessTokenTest.php
  tests/Unit/Db/AuthorizationCodeTest.php
  tests/Unit/Panel/AdminPanelTest.php
  vendor-bin/behat/composer.json
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#260 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/AppInfo/Application.php
  lib/AuthModule.php
  lib/BackgroundJob/CleanUp.php
  lib/Commands/AddClient.php
  lib/Controller/OAuthApiController.php
  lib/Controller/PageController.php
  lib/Db/AccessTokenMapper.php
  lib/Db/AuthorizationCodeMapper.php
  lib/Db/RefreshTokenMapper.php
  lib/Hooks/UserHooks.php
  lib/Sabre/AbstractBearer.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#265 Adjust drone pipelines for PHP 7.4
  .drone.star
Labels: 3 - To review, QA-ready
